function fig = plotAttitudeGravityProvenanceView(audit, cfg)
%PLOTATTITUDEGRAVITYPROVENANCEVIEW Plot attitude/gravity acceleration evidence.
arguments
    audit table
    cfg struct = caelum.defaultConfig()
end

if isempty(audit) || height(audit) < 1
    error('caelum:plotAttitudeGravityProvenanceView:EmptyAudit', ...
        'Attitude/gravity provenance audit table must contain at least one row.');
end

required = [ ...
    "t", ...
    "logged_a_vertical_mps2", ...
    "smoothed_a_vertical_mps2", ...
    "gravity_projected_a_vertical_mps2", ...
    "attitude_a_vertical_mps2", ...
    "accel_norm_mps2", ...
    "logged_g_bx_mps2", ...
    "logged_g_by_mps2", ...
    "logged_g_bz_mps2", ...
    "logged_g_norm_mps2", ...
    "attitude_g_norm_mps2", ...
    "logged_roll_deg", ...
    "logged_pitch_deg", ...
    "replay_roll_deg", ...
    "replay_pitch_deg", ...
    "replay_yaw_deg", ...
    "gravity_update_used", ...
    "gravity_innovation", ...
    "gravity_residual_mps2", ...
    "tilt_error_deg", ...
    "logged_minus_attitude_a_vertical_mps2", ...
    "projected_minus_logged_a_vertical_mps2", ...
    "attitude_minus_projected_a_vertical_mps2", ...
    "attitude_truth_error_a_vertical_mps2", ...
    "gravity_residual_warn_mps2", ...
    "evidence_code", ...
    "evidence_label", ...
    "evidence_rationale"];
missing = setdiff(required, string(audit.Properties.VariableNames), 'stable');
if ~isempty(missing)
    error('caelum:plotAttitudeGravityProvenanceView:MissingAuditFields', ...
        'Attitude/gravity audit table is missing required fields: %s', ...
        strjoin(cellstr(missing), ', '));
end

if isempty(fieldnames(cfg))
    cfg = caelum.defaultConfig();
end

theme = localTheme();
fig = figure('Name', 'Caelum Attitude / Gravity / Vertical-Acceleration Provenance', ...
    'Color', theme.figureColor, ...
    'Units', 'normalized', ...
    'Position', [0.03 0.06 0.94 0.88]);

tl = tiledlayout(fig, 5, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
hTitle = title(tl, 'Attitude / Gravity / Vertical-Acceleration Provenance View');
hTitle.Color = theme.textColor;

axVertical = nexttile(tl, 1, [1 2]);
localPlotVerticalAcceleration(axVertical, audit, theme);

axAccelNorm = nexttile(tl, 3);
localPlotAccelNormGate(axAccelNorm, audit, cfg, theme);

axGravity = nexttile(tl, 4);
localPlotGravityEvidence(axGravity, audit);

axAngles = nexttile(tl, 5);
localPlotAttitudeAngles(axAngles, audit);

axUpdate = nexttile(tl, 6);
localPlotUpdateEvidence(axUpdate, audit);

axDeltas = nexttile(tl, 7);
localPlotVerticalAccelDeltas(axDeltas, audit);

axClass = nexttile(tl, 8);
localPlotEvidenceLabels(axClass, audit);

axSummary = nexttile(tl, 9, [1 2]);
localPlotSummary(axSummary, audit);

localApplyStyle(fig, theme);
end

function localPlotVerticalAcceleration(ax, audit, theme)
hold(ax, 'on');
plot(ax, audit.t, audit.logged_a_vertical_mps2, ...
    'LineWidth', 1.1, ...
    'DisplayName', 'logged a_{vertical}');
plot(ax, audit.t, audit.smoothed_a_vertical_mps2, ...
    'LineWidth', 1.0, ...
    'DisplayName', 'smoothed logged a_{vertical}');
plot(ax, audit.t, audit.gravity_projected_a_vertical_mps2, '--', ...
    'LineWidth', 1.0, ...
    'DisplayName', 'raw accel projected on logged gravity');
plot(ax, audit.t, audit.attitude_a_vertical_mps2, ':', ...
    'LineWidth', 1.2, ...
    'DisplayName', 'attitude-derived a_{vertical}');

if ismember("truth_a_vertical_mps2", string(audit.Properties.VariableNames)) && any(isfinite(audit.truth_a_vertical_mps2))
    plot(ax, audit.t, audit.truth_a_vertical_mps2, '-.', ...
        'Color', theme.truthColor, ...
        'LineWidth', 1.0, ...
        'DisplayName', 'truth a_{vertical}');
end

xlabel(ax, 't [s]');
ylabel(ax, 'm/s^2');
title(ax, 'Vertical Acceleration Provenance');
grid(ax, 'on');
legend(ax, 'Location', 'best');
end

function localPlotAccelNormGate(ax, audit, cfg, theme)
hold(ax, 'on');
g = localConfigScalar(cfg, "gravity", 9.8);
tol = localFirstFinite(audit.gravity_residual_warn_mps2);
if ~isfinite(tol)
    tol = 2.0;
end
plot(ax, audit.t, audit.accel_norm_mps2, ...
    'LineWidth', 1.1, ...
    'DisplayName', '|a_{body}|');
yline(ax, g, '-', ...
    'Color', theme.truthColor, ...
    'DisplayName', 'gravity');
yline(ax, g + tol, '--', ...
    'Color', theme.warningColor, ...
    'DisplayName', '+ residual warn');
yline(ax, g - tol, '--', ...
    'Color', theme.warningColor, ...
    'DisplayName', '- residual warn');
plot(ax, audit.t, audit.gravity_residual_mps2, ':', ...
    'LineWidth', 1.0, ...
    'DisplayName', '|a|-g residual');
xlabel(ax, 't [s]');
ylabel(ax, 'm/s^2');
title(ax, 'Accelerometer Norm / Gravity Gate');
grid(ax, 'on');
legend(ax, 'Location', 'best');
end

function localPlotGravityEvidence(ax, audit)
hold(ax, 'on');
plot(ax, audit.t, audit.logged_g_norm_mps2, ...
    'LineWidth', 1.1, ...
    'DisplayName', 'logged |g_b|');
plot(ax, audit.t, audit.attitude_g_norm_mps2, '--', ...
    'LineWidth', 1.1, ...
    'DisplayName', 'attitude |g_b|');
plot(ax, audit.t, audit.logged_g_bx_mps2, ':', ...
    'LineWidth', 0.9, ...
    'DisplayName', 'logged g_x');
plot(ax, audit.t, audit.logged_g_by_mps2, ':', ...
    'LineWidth', 0.9, ...
    'DisplayName', 'logged g_y');
plot(ax, audit.t, audit.logged_g_bz_mps2, ':', ...
    'LineWidth', 0.9, ...
    'DisplayName', 'logged g_z');
xlabel(ax, 't [s]');
ylabel(ax, 'm/s^2');
title(ax, 'Logged vs. Replayed Gravity Evidence');
grid(ax, 'on');
legend(ax, 'Location', 'best');
end

function localPlotAttitudeAngles(ax, audit)
hold(ax, 'on');
plot(ax, audit.t, audit.replay_roll_deg, ...
    'LineWidth', 1.0, ...
    'DisplayName', 'replay roll');
plot(ax, audit.t, audit.replay_pitch_deg, ...
    'LineWidth', 1.0, ...
    'DisplayName', 'replay pitch');
plot(ax, audit.t, audit.replay_yaw_deg, ...
    'LineWidth', 1.0, ...
    'DisplayName', 'replay yaw');

if ismember("logged_roll_deg", string(audit.Properties.VariableNames)) && any(isfinite(audit.logged_roll_deg))
    plot(ax, audit.t, audit.logged_roll_deg, '--', ...
        'LineWidth', 0.9, ...
        'DisplayName', 'logged roll');
    plot(ax, audit.t, audit.logged_pitch_deg, '--', ...
        'LineWidth', 0.9, ...
        'DisplayName', 'logged pitch');
end

if ismember("truth_roll_deg", string(audit.Properties.VariableNames)) && any(isfinite(audit.truth_roll_deg))
    plot(ax, audit.t, audit.truth_roll_deg, ':', ...
        'LineWidth', 0.9, ...
        'DisplayName', 'truth roll');
    plot(ax, audit.t, audit.truth_pitch_deg, ':', ...
        'LineWidth', 0.9, ...
        'DisplayName', 'truth pitch');
end

xlabel(ax, 't [s]');
ylabel(ax, 'deg');
title(ax, 'Attitude Angles');
grid(ax, 'on');
legend(ax, 'Location', 'best');
end

function localPlotUpdateEvidence(ax, audit)
hold(ax, 'on');
yyaxis(ax, 'left');
stairs(ax, audit.t, double(audit.gravity_update_used), ...
    'LineWidth', 1.1, ...
    'DisplayName', 'gravity update used');
if ismember("attitude_fallback_used", string(audit.Properties.VariableNames))
    stairs(ax, audit.t, 0.5 .* double(audit.attitude_fallback_used), '--', ...
        'LineWidth', 1.0, ...
        'DisplayName', 'attitude input fallback');
end
ylim(ax, [-0.05 1.05]);
ylabel(ax, 'flag');

yyaxis(ax, 'right');
plot(ax, audit.t, audit.gravity_innovation, ...
    'LineWidth', 1.0, ...
    'DisplayName', 'gravity innovation');
plot(ax, audit.t, audit.tilt_error_deg, ':', ...
    'LineWidth', 1.0, ...
    'DisplayName', 'tilt error');
ylabel(ax, 'innovation / deg');

xlabel(ax, 't [s]');
title(ax, 'Gravity Update Evidence');
grid(ax, 'on');
legend(ax, 'Location', 'best');
end

function localPlotVerticalAccelDeltas(ax, audit)
hold(ax, 'on');
plot(ax, audit.t, audit.logged_minus_attitude_a_vertical_mps2, ...
    'LineWidth', 1.0, ...
    'DisplayName', 'logged - attitude');
plot(ax, audit.t, audit.projected_minus_logged_a_vertical_mps2, '--', ...
    'LineWidth', 1.0, ...
    'DisplayName', 'projected - logged');
plot(ax, audit.t, audit.attitude_minus_projected_a_vertical_mps2, ':', ...
    'LineWidth', 1.0, ...
    'DisplayName', 'attitude - projected');
if ismember("attitude_truth_error_a_vertical_mps2", string(audit.Properties.VariableNames)) && ...
        any(isfinite(audit.attitude_truth_error_a_vertical_mps2))
    plot(ax, audit.t, audit.attitude_truth_error_a_vertical_mps2, '-.', ...
        'LineWidth', 1.0, ...
        'DisplayName', 'attitude - truth');
end
xlabel(ax, 't [s]');
ylabel(ax, 'm/s^2');
title(ax, 'Vertical Acceleration Delta Evidence');
grid(ax, 'on');
legend(ax, 'Location', 'best');
end

function localPlotEvidenceLabels(ax, audit)
stairs(ax, audit.t, audit.evidence_code, ...
    'LineWidth', 1.2, ...
    'DisplayName', 'attitude/gravity evidence label');
yticks(ax, 1:12);
yticklabels(ax, localEvidenceTickLabels());
ylim(ax, [0.5 12.5]);
xlabel(ax, 't [s]');
title(ax, 'Audit Classification');
grid(ax, 'on');
end

function labels = localEvidenceTickLabels()
labels = { ...
    'telemetry incomplete', ...
    'sample gap', ...
    'logged gravity norm bad', ...
    'attitude gravity norm bad', ...
    'tilt error high', ...
    'gravity residual high', ...
    'vertical accel disagreement', ...
    'truth accel error high', ...
    'attitude evidence missing', ...
    'gravity update used', ...
    'attitude propagated', ...
    'nominal'};
end

function localPlotSummary(ax, audit)
axis(ax, [0 1 0 1]);
axis(ax, 'off');

dt = localSampleDurations(audit.t);
gravityUpdateFraction = mean(double(audit.gravity_update_used), 'omitnan');
rmseLoggedAttitude = localRmse(audit.logged_minus_attitude_a_vertical_mps2);
rmseProjectedLogged = localRmse(audit.projected_minus_logged_a_vertical_mps2);
rmseAttitudeTruth = localRmse(audit.attitude_truth_error_a_vertical_mps2);
maxTilt = max(audit.tilt_error_deg, [], 'omitnan');
maxGravityResidual = max(abs(audit.gravity_residual_mps2), [], 'omitnan');

lines = strings(0, 1);
lines(end+1) = "Attitude / Gravity Summary";
lines(end+1) = sprintf('Rows: %d | duration: %.3f s', height(audit), sum(dt, 'omitnan'));
lines(end+1) = sprintf('Gravity update fraction: %.3f', gravityUpdateFraction);
lines(end+1) = sprintf('Max tilt error: %.3f deg | max gravity residual: %.3f m/s^2', ...
    maxTilt, maxGravityResidual);
lines(end+1) = sprintf('Vertical accel RMSE: logged-attitude=%.3f m/s^2 | projected-logged=%.3f m/s^2', ...
    rmseLoggedAttitude, rmseProjectedLogged);
if isfinite(rmseAttitudeTruth)
    lines(end+1) = sprintf('Attitude-vs-truth vertical accel RMSE: %.3f m/s^2', ...
        rmseAttitudeTruth);
end
lines(end+1) = sprintf('Final logged/replay attitude: roll %.2f/%.2f deg, pitch %.2f/%.2f deg', ...
    localLastFinite(audit.logged_roll_deg), localLastFinite(audit.replay_roll_deg), ...
    localLastFinite(audit.logged_pitch_deg), localLastFinite(audit.replay_pitch_deg));
lines(end+1) = sprintf('Final gravity norms: logged %.3f m/s^2 | attitude %.3f m/s^2', ...
    localLastFinite(audit.logged_g_norm_mps2), localLastFinite(audit.attitude_g_norm_mps2));

labels = unique(audit.evidence_label, 'stable');
labelCounts = strings(numel(labels), 1);
for k = 1:numel(labels)
    labelCounts(k) = sprintf('%s=%d', labels(k), nnz(audit.evidence_label == labels(k)));
end
lines(end+1) = "Evidence labels: " + strjoin(labelCounts, "; ");

idx = find(audit.evidence_label ~= "", 1, 'last');
if ~isempty(idx)
    lines(end+1) = "Final label: " + audit.evidence_label(idx);
    lines(end+1) = "Final rationale: " + audit.evidence_rationale(idx);
end

text(ax, 0.02, 0.96, strjoin(lines, newline), ...
    'VerticalAlignment', 'top', ...
    'FontName', 'Consolas', ...
    'FontSize', 8, ...
    'Interpreter', 'none');
end

function dt = localSampleDurations(t)
t = t(:);
dt = [diff(t); NaN];
fallback = median(diff(t), 'omitnan');
if ~isfinite(fallback) || fallback < 0
    fallback = 0;
end
bad = ~isfinite(dt) | dt < 0;
dt(bad) = fallback;
end

function value = localRmse(x)
valid = isfinite(x);
if ~any(valid)
    value = NaN;
else
    value = sqrt(mean(x(valid).^2, 'omitnan'));
end
end

function value = localFirstFinite(x)
idx = find(isfinite(x), 1, 'first');
if isempty(idx)
    value = NaN;
else
    value = x(idx);
end
end

function value = localLastFinite(x)
idx = find(isfinite(x), 1, 'last');
if isempty(idx)
    value = NaN;
else
    value = x(idx);
end
end

function value = localConfigScalar(cfg, fieldName, defaultValue)
if isstruct(cfg) && isfield(cfg, fieldName) && isfinite(cfg.(fieldName))
    value = cfg.(fieldName);
else
    value = defaultValue;
end
end

function theme = localTheme()
theme.figureColor = [0.07 0.08 0.09];
theme.axesColor = [0.06 0.06 0.06];
theme.textColor = [0.92 0.92 0.92];
theme.gridColor = [0.38 0.38 0.38];
theme.panelEdgeColor = [0.28 0.31 0.34];
theme.truthColor = [0.84 0.78 0.24];
theme.warningColor = [0.93 0.43 0.18];
end

function localApplyStyle(fig, theme)
axesHandles = findall(fig, 'Type', 'axes');
for k = 1:numel(axesHandles)
    ax = axesHandles(k);
    set(ax, ...
        'Color', theme.axesColor, ...
        'XColor', theme.textColor, ...
        'YColor', theme.textColor, ...
        'ZColor', theme.textColor, ...
        'GridColor', theme.gridColor, ...
        'MinorGridColor', theme.gridColor);
end

textHandles = findall(fig, 'Type', 'text');
for k = 1:numel(textHandles)
    set(textHandles(k), 'Color', theme.textColor);
end

legendHandles = findall(fig, 'Type', 'legend');
for k = 1:numel(legendHandles)
    try
        set(legendHandles(k), ...
            'Color', theme.axesColor, ...
            'TextColor', theme.textColor, ...
            'EdgeColor', theme.panelEdgeColor);
    catch
    end
end
end
